### ISSUE TITLE
Left over old build files in npm release

### ISSUE THREAD

**Issue by zoton2** [frozencure/twitch-player#3]
**Describe the bug**
Not exactly a bug in relation to the repository but while attempting to debug another bug I found what appears to be left over files from an earlier build no longer used in `build/main/lib/video` in the npm release, unless I missed their use somewhere?

**To Reproduce**
1. Install the npm version of this repository.
2. Inspect the downloaded files.

**Expected behavior**
The files to not be there on download.

**Screenshots**
![image](https://user-images.githubusercontent.com/13722551/97086333-769ea000-161a-11eb-9b13-3154d07b3cf1.png)

**Comment by frozencure** [comment]
Oh you're right, I forgot to rebuild the project before I published it. I'll publish a new version shortly. Thanks for noticing :)

**Comment by zoton2** [comment]
I think you did rebuild it, just not cleanly, as there are updated files in there (even the ones from a couple hours ago I think?).

**Comment by frozencure** [comment]
Yeah you're right, I manually removed the build folder and the build worked as expected.
